### ISSUE TITLE
Cannot use framework in AppClip

### ISSUE THREAD

**Issue by appfrilans** [AsyncSwift/AsyncLocationKit#21]
Just by importing the library into my app Clip Target in Xcode I get the following error/warning when uploading to TestFlight/AppStore:

ITMS-90842: Invalid SDK usage - App clip 'BuildTarget_AC_Base.app/AppClips/BuildTarget_AppClip.app' uses the SDK selector 'requestAlwaysAuthorization', which is not supported. Ensure your app clip is using supported SDK features.

In the rest of my code I use a "#if APPCLIP" to skip code that reference API that are not allowed in AppClips. Is it possible to solve this in the framework as well?

**Comment by gre4ixin** [comment]
https://github.com/AsyncSwift/AsyncLocationKit/pull/22

**Comment by ay8s** [comment]
Thanks @gre4ixin. Curious if I'm missing a trick to allow APPCLIP to be passed to the Swift Package? Seems like the App Clip always has requestAlwaysAuthorization defined causing submission errors despite it being defined for the target.

**Comment by appfrilans** [comment]
As I mentioned in the PR, I do not think this fix works. Compiler flags are not accessible from the external packages. Not sure how to solve this one.

**Comment by wtpalexander** [comment]
@appfrilans - Any luck finding a solution for using this package in an App Clip?

**Comment by ay8s** [comment]
@wtpalexander I ended up just implementing it directly into my project to ensure the AppClip checks work. Since then I've shifted over to using https://developer.apple.com/documentation/corelocation/cllocationupdate/4211321-liveupdates to retrieve a single location.

**Comment by wtpalexander** [comment]
@ay8s - Thanks for the info! Also thanks for the link - looks like a good substitute for this situation, thanks!
