### ISSUE TITLE
development branch

### ISSUE THREAD

**Issue by RomanPodymov** [AsyncSwift/AsyncLocationKit#36]
Hello.
Thank you for AsyncLocationKit.
Would you delete `development`? I see all pull requests are using `main` as target. Or what is the purpose of `development`?

**Comment by gre4ixin** [comment]
> Hello.
> 
> Thank you for AsyncLocationKit.
> 
> Would you delete `development`? I see all pull requests are using `main` as target. Or what is the purpose of `development`?

@RomanPodymov yes, you're right, the development branch has been used for a long time, I'll delete it when I get to the computer)

**Comment by gre4ixin** [comment]
done  ✅
