### ISSUE TITLE
locationManager.requestLocation

### ISSUE THREAD

**Issue by NrmeenTomoum** [AsyncSwift/AsyncLocationKit#39]
locationManager.requestLocation never returned even it didn't throw any error @humblehacker

**Comment by TopOneLee** [comment]
I also encountered the same problem. What solution did you use?

**Comment by kubastick** [comment]
@NrmeenTomoum @TopOneLee 
I've had the same issue and it turned out that I didn't initialized AsyncLocationManager on the main thread.
Adding the `@MainActor` attribute to the location function solved this issue for me.

Example code:
```swift
@MainActor // <- Perform this task on main thread
func getCurrentLocation() async throws -> CLLocation {
  var locationManager = AsyncLocationManager()
  // Do rest of the work here
}
```

**Comment by gre4ixin** [comment]
> locationManager.requestLocation never returned even it didn't throw any error @humblehacker

If you call `requestLocation()` from `Task`, then the error will not get into the result, because the `Task` inside has a throws closure using `do { } catch { }` the error will end up in `catch`

**Comment by larrylegend** [comment]
This nuance caught me too. 
@kubastick thanks for the solution!
@gre4ixin thanks for the very helpful library!
